### PR TITLE
Use bem-xjst in Node.js without bundling via browserify (#407 fixed)

### LINKED ISSUE #407: Use bem-xjst in Node.js without bundling via browserify

### PR DESCRIPTION
**Pull request by miripiruni**
Fixes #407 

## Changes proposed in this pull request

- use required bem-xjst instead of bundled
- All public API not changed

## API Demo (compile(), apply(), generate())

```js
$ cat test.js
var bemhtml = require('./').bemhtml;
var libs = {
  jscs: require('jscs'),
  chai: require('chai')
};

var templates = function templates() {
  block('a').content()(function() {

    console.log(this.require('chai').version);
    console.log(this.chai.version);

    return applyNext();
  });
};

var htmlTemplates = bemhtml.compile(templates);

htmlTemplates.BEMContext.prototype.require = function require(libName) {
  return libs[libName];
};

htmlTemplates.BEMContext.prototype.chai = require('chai');

var bemjson = { block: 'a', content: 'First' };

console.log(htmlTemplates.apply(bemjson));

htmlTemplates.compile(function() {
  block('a').mix()('mixed');
});
console.log(htmlTemplates.apply(bemjson));

require('fs').writeFileSync('bemhtml-runtime.js', bemhtml.generate(function() {
  block('a').tag()('span');
}, { runtimeLint: true }));
```

```
$ node test
3.5.0
3.5.0
<div class="a">First</div>
3.5.0
3.5.0
<div class="a mixed">First</div>
```

```
$ node
> var b = require('./bemhtml-runtime')
undefined
> var t = b.compile()
undefined
> t.apply({block:'a'})
'<span class="a"></span>'
> t.apply({block:'a__b'})

BEM-XJST WARNING: wrong block name.
Block name can not contain modifier delimeter nor elem delimeter.
block: a__b
ctx: {"block":"a__b"}

>
(To exit, press ^C again or type .exit)
>
```

### CODE REVIEW

**Comment by zxqfox** [comment]
@miripiruni What you think about trying to bundle with `rollup + rollup-plugin-node-resolve + rollup-plugin-commonjs`? Guess we should get a try.

File: index.js [hunk 1]
```diff
@@ -1,20 +1,15 @@
-var fs = require('fs');
-var Compiler = require('./lib/compiler').Compiler;
+var Compiler = require('./lib/compiler');
 var _cache = {};
 
-function getEngine(engineName) {
-  if (_cache[engineName]) return _cache[engineName];
+var getEngine = function getEngine(engineName) {
```
Comment (zxqfox) [inline index.js]: Do we really need `var getEngine`?

File: index.js [hunk 2]
```diff
@@ -1,20 +1,15 @@
...
+};
 
-  return _cache[engineName] = new Compiler(runtime);
-}
 
 module.exports = {
-  get bemtree() { return getEngine('bemtree'); },
-  get bemhtml() { return getEngine('bemhtml'); }
+  get bemhtml() { return getEngine('bemhtml'); },
+  get bemtree() { return getEngine('bemtree'); }
```
Comment (zxqfox) [inline index.js]: why you swap them? ;-)

File: lib/bemxjst/index.js [hunk 3]
```diff
@@ -519,7 +524,8 @@ BEMXJST.prototype.exportApply = function exportApply(exports) {
 
   // Add templates at run time
   exports.compile = function compile(templates) {
-    return self.compile(templates);
+    self.compile(templates);
+    return exports;
```
Comment (zxqfox) [inline lib/bemxjst/index.js]: Not sure it's a good behaviour at all, some times better to have immutable instances with templates.

File: index.js (hunk 2 above)
Comment (miripiruni) [inline index.js]: @zxqfox I just wrote it from scratch, I can swap back =)

File: lib/bemxjst/index.js (hunk 3 above)
Comment (miripiruni) [inline lib/bemxjst/index.js]: @tadatuta what reason to do so? Only inconcistency between compiles? #408

**Comment by miripiruni** [comment]
@zxqfox I’ll try `rollup`, thanks.

File: lib/bemxjst/index.js (hunk 3 above)
Comment (zxqfox) [inline lib/bemxjst/index.js]: Nah, just lack a way to the same as original compile — make an instance with templates in runtime or get templates from bundled one.

**Comment by zxqfox** [comment]
Looks good at all, but I'm not sure about bundled version. Don't know how to quickly check it

**Comment by miripiruni** [comment]
@zxqfox see PR’s description. I provide logs from my bundle test. Template bundling, bem-xjst options and etc works.

File: index.js [hunk 4]
```diff
@@ -1,18 +1,13 @@
...
-  if (_cache[engineName]) return _cache[engineName];
+  if (_cache[engineName])
+    return _cache[engineName];
 
-  var runtime = require('./lib/' + engineName);
-  var pathToBundle = require.resolve('./lib/' + engineName + '/bundle');
-  var sourceBundle = fs.readFileSync(pathToBundle, 'utf8');
-
-  runtime.source = sourceBundle;
+  return _cache[engineName] = new Compiler(engineName);
```
Comment (miripiruni) [inline index.js]: ||

File: lib/bemxjst/index.js [hunk 5]
```diff
@@ -115,12 +115,17 @@ BEMXJST.prototype.compile = function compile(code) {
   this.oninit = out.oninit;
 };
 
+BEMXJST.prototype.getTemplate = function(code, options) {
+  var templates = {};
+  this.compile(code, options);
+  this.exportApply(templates);
```
Comment (miripiruni) [inline lib/bemxjst/index.js]: return this.exportApply();

File: lib/bemxjst/index.js [hunk 6]
```diff
@@ -115,12 +115,17 @@ BEMXJST.prototype.compile = function compile(code) {
...
+  return templates;
+};
+
 BEMXJST.prototype.recompileInput = function recompileInput(code) {
   var args = BEMXJST.prototype.locals;
-  var out = code.toString();
-
-  // Strip the function
-  out = out.replace(/^function[^{]+{|}$/g, '');
+  var out = code ? utils.fnToString(code) : '';
```
Comment (miripiruni) [inline lib/bemxjst/index.js]: var out = utils.fnToString(code)

File: lib/compiler.js [hunk 7]
```diff
@@ -1,41 +1,56 @@
...
-exports.Compiler = Compiler;
+Compiler.prototype.compile = function compile(code, options) {
+  if (!options) options = {};
+
+  var api = new engines[this.engineName](options);
+
+  if (options.runtimeLint) {
+    code = fnToString(code);
+    code = code + ';' + require('fs')
+      .readFileSync('./runtime-lint/index.js', 'utf8');
```
Comment (miripiruni) [inline lib/compiler.js]: use require

File: lib/compiler.js [hunk 8]
```diff
@@ -1,41 +1,56 @@
...
 }
 
-exports.Compiler = Compiler;
+Compiler.prototype.compile = function compile(code, options) {
+  if (!options) options = {};
+
+  var api = new engines[this.engineName](options);
+
+  if (options.runtimeLint) {
+    code = fnToString(code);
```
Comment (miripiruni) [inline lib/compiler.js]: code = fnToString() + …

File: lib/compiler.js [hunk 9]
```diff
@@ -1,41 +1,56 @@
...
+
+  var exportName = this.engineName.toUpperCase();
 
   var source = [
     '/// -------------------------------------',
     '/// --------- BEM-XJST Runtime Start ----',
     '/// -------------------------------------',
     'var ' + exportName + ' = function(module, exports) {',
-    this.runtime.source + ';',
+    bundleSource + ';',
```
Comment (miripiruni) [inline lib/compiler.js]: заинлайнить

File: lib/compiler.js [hunk 10]
```diff
@@ -1,41 +1,56 @@
...
   if (!options) options = {};
-
   code = fnToString(code);
 
-  var exportName = options.exportName || 'BEMHTML';
-  var engine = options.engine || 'BEMHTML';
-
-  var locals = this.runtime.prototype.locals;
+  var fs = require('fs');
+  var locals = require('./bemxjst').prototype.locals;
```
Comment (miripiruni) [inline lib/compiler.js]: заинлайнить
