### PR TITLE
BEMTREE: special unescaped html field from BEMJSON should render as is

### LINKED ISSUE #399: Wrong html field handling in BEMTREE
### Input code or something about issue background

There's no way to keep unescaped markup when using `BEMHTML.apply(BEMTREE.apply())`.

### Expected Behavior
```js
BEMTREE.apply({ block: 'b1', content: { html: '<br>' } });
// { block: 'b1', content: { html: '<br>' } }
```
### Actual Behavior
```js
BEMTREE.apply({ block: 'b1', content: { html: '<br>' } });
// { block: 'b1', content: '<br>' }
```
### Possible Solution

This [piece of code](https://github.com/bem/bem-xjst/blob/master/lib/bemxjst/index.js#L280-L288) should only be applied to BEMHTML and not to BEMTREE.

### Your Environment

bem-xjst 7.x

### PR DESCRIPTION
**Pull request by miripiruni**
Fixes #399

### CODE REVIEW

File: lib/bemtree/index.js [hunk 1]
```diff
@@ -54,3 +54,8 @@ BEMTREE.prototype._run = function _run(context) {
   if (!context || context === true) return context;
   return BEMXJST.prototype._run.call(this, context);
 };
+
+BEMTREE.prototype.runUnescaped = function runUnescaped(context) {
```
Comment (miripiruni) [inline lib/bemtree/index.js]: The method overrides base BEMXJST method.
