### PR TITLE
[4.x] Compiled bundle is broken after minification.

### LINKED ISSUE #101: [4.x] Compiled bundle is broken after minification
How to reproduce:

```js
var fs = require('fs'),
    bemxjst = require('bem-xjst'), // 4.2.3
    uglify = require('uglify-js'), // 2.4.24
    bemjson = { block: 'b1' },
    tmpl = function() {
        block('b1').tag()('ololo');
    };

fs.writeFileSync('tmpl.js', bemxjst.generate(tmpl));

console.log(require('./tmpl').apply(bemjson)); // <ololo class="b1"></ololo>

fs.writeFileSync('tmpl.min.js', uglify.minify('tmpl.js').code);

require('./tmpl.min').apply(bemjson);

// <ololo class="b1"></ololo>
// undefined:3
// s("b1").tag()("ololo")
// ^

// ReferenceError: s is not defined
//     at Object.eval (eval at <anonymous> (/Users/tadatuta/Sites/bem-xjst-uglify-bug/tmpl.min.js:1:6089), <anonymous>:3:1)
//     at d.build (/Users/tadatuta/Sites/bem-xjst-uglify-bug/tmpl.min.js:1:18392)
//     at n.compile (/Users/tadatuta/Sites/bem-xjst-uglify-bug/tmpl.min.js:1:5559)
//     at Object.<anonymous> (/Users/tadatuta/Sites/bem-xjst-uglify-bug/tmpl.min.js:1:22037)
//     at Module._compile (module.js:434:26)
//     at Object.Module._extensions..js (module.js:452:10)
//     at Module.load (module.js:355:32)
//     at Function.Module._load (module.js:310:12)
//     at Module.require (module.js:365:17)
//     at require (module.js:384:17)
```

### PR DESCRIPTION
**Pull request by veged**
close #101

### CODE REVIEW

File: lib/bemhtml/runtime/index.js [hunk 1]
```diff
@@ -116,12 +116,12 @@ BEMHTML.prototype.compile = function compile(code) {
...
 
-  var args = BEMHTML.locals.join(', ');
+  var args = BEMHTML.locals;
   if (typeof code === 'function') {
-    var start = out.match(/^function([^{]+){/);
+    var start = out.match(/^function\s*\(([^{]+)\)\s*{/);
 
     // Reuse function if it already has right arguments
-    if (start !== null && start[1].indexOf('(' + args + ')') !== -1)
+    if (start !== null && start[1].split(/,\s*/).length === args.length)
```
Comment (indutny) [inline lib/bemhtml/runtime/index.js]: `code.length`?

Comment (veged) [inline lib/bemhtml/runtime/index.js]: yeah!

BTW, what another cases of args was covered by previous version?

Comment (indutny) [inline lib/bemhtml/runtime/index.js]: No other cases, it was just checking their names.
